{% set data = load_setup_py_data() %}

package:
  name: baseless
  version: {{ data.get('version') }}

source:
  path: ..
  git_url: https://github.com/cvdelannoy/baseLess.git

build:
  entry_points:
    - baseLess = baseLess.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.8
    - matplotlib=3.5.1  # avoid issues with heatmaps
    - tensorflow-gpu=2.8.1
    - pandas=1.4.2
    - bokeh=2.4.3
    - snakemake=7.8.1
    - h5py=3.6.0
    - zodb=5.7.0
    - hyperopt=0.2.7
    - seaborn=0.11.2
    - numpy=1.22.4
    - pytables=3.7.0
    - kmer-jellyfish=2.3.0
    - scikit-learn=1.1.1
    - fastparquet=0.8.1

about:
  home: https://github.com/cvdelannoy/baseLess
  summary: {{ data['description'] }}
  dev_url: {{ data['url'] }}