{% set data = load_setup_py_data() %}

package:
  name: baseless
  version: {{ data.get('version') }}

source:
  git_url: git@github.com:cvdelannoy/baseLess.git

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - baseLess = baseLess.__main__:main
    - baseLess_inference = baseLess.inference.run_inference:main

extra:
  channels:
    - bokeh
    - bioconda
    - conda-forge

requirements:
  build:
    - python==3.10  # something betweeen 3.9 and 3.10 causes installation errors if version is not enforced...
    - setuptools

  run:
    - python==3.10
    - Cython==0.29.30
    - matplotlib==3.5.1  # avoid issues with heatmaps
    - tensorflow-gpu==2.8.1
    - pandas==1.4.2
    - bokeh==2.4.3
    - snakemake==7.8.1
    - h5py==3.6.0
    - zodb==5.7.0
    - hyperopt==0.2.7
    - seaborn==0.11.2
    - numpy==1.22.4
    - pytables==3.7.0
    - kmer-jellyfish==2.3.0
    - scikit-learn==1.1.1
    - fastparquet==0.8.1

about:
  home: https://github.com/cvdelannoy/baseLess
  summary: {{ data['description'] }}
  dev_url: {{ data['url'] }}